version: '3'
services:
  neo4j:
    build: ./neo4j
    image: cybera/adi-neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - default
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_memory_heap_maxSize: 2048
      NEO4J_dbms_memory_pagecache_size: 1048576
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_apoc_autoIndex_enabled: "true"
      NEO4J_com_graphaware_runtime_enabled: "true"
      NEO4J_com_graphaware_module_UIDM_1: "com.graphaware.module.uuid.UuidBootstrapper"
  server:
    build: ./server
    image: cybera/adi-server:latest
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - ./config/development.toml:/usr/src/app/config/development.toml
      - ./data/uploads:/mnt/data
      - ./data/scripts:/mnt/scripts
      - server_node_modules:/usr/src/app/node_modules
    networks:
      - default
    command: npm run devStart
  client:
    build: ./client
    ports:
      - "8080:8080"
      - "8888:8888"
    volumes:
      - ./client:/usr/src/app
      - client_node_modules:/usr/src/app/node_modules
    networks:
      - default
  queue:
    image: rabbitmq:3.7
    networks:
      - default
  python-worker:
    build: ./services/python-worker
    image: cybera/adi-python-worker:latest
    networks:
      - default
    volumes:
      - ./services/python-worker:/usr/src/app
      - ./config/development.toml:/usr/src/app/config/development.toml
      - ./data/uploads:/mnt/data
      - ./data/scripts:/mnt/scripts
    depends_on:
      - queue
  manual:
    build: ./manual
    image: cybera/adi-manual:latest
    ports:
      - "4000:4000"
      - "35729:35729"
    networks:
      - default
    volumes:
      - ./manual/src:/usr/src/app
      - ./manual/outputs:/usr/src/outputs
      - manual_node_modules:/usr/src/app/node_modules
      - manual_gitbook_comp:/usr/src/app/_book
    command: gitbook serve
  redis:
    image: redis:4.0
    networks:
      - default

volumes:
  neo4j_data:
  server_node_modules:
  client_node_modules:
  manual_node_modules:
  manual_gitbook_comp:
